### PR TITLE
Add ICC Profile Embedding Support for WebP Encoding

### PR DESCRIPTION
**Pull request by KYHyeon**
# Add ICC Profile Embedding Support for WebP Encoding

Fixes #119

## Problem

When encoding images with wide color gamut (Display P3, Adobe RGB) to WebP, the ICC color profile was not embedded in the output file. This caused colors to appear washed out on Android devices and web browsers that assume sRGB.

### Before
```
00000000  52 49 46 46 c2 26 00 00  57 45 42 50 56 50 38 20  |RIFF.&..WEBPVP8 |
                                                      ^^^^
                                                      VP8 (Simple Format)
→ No VP8X, no ICCP chunk
→ Display P3 colors interpreted as sRGB → washed out
```

### After
```
00000000  52 49 46 46 f4 28 00 00  57 45 42 50 56 50 38 58  |RIFF.(..WEBPVP8X|
                                                      ^^^^
00000010  0a 00 00 00 20 00 00 00  e7 03 00 e7 03 00 49 43  |.... .........IC|
                    ^^                                ^^^^
                    0x20 (ICCP_FLAG)                  ICCP chunk
00000020  43 50 18 02 00 00 ...                             |CP........

→ VP8X Extended Format with ICCP_FLAG (0x20)
→ ICCP chunk contains Display P3 profile (536 bytes)
→ Colors display correctly on all platforms
```

## Implementation

**Key points:**

1. **Uses WebPMux API** to embed ICCP chunk following libwebp examples
2. **Performance optimized** with `copy_data=0` - avoids redundant 10MB+ memory copies
3. **Skips ICC when `maxFileSize` is set** - size limit takes priority over color accuracy
4. **iOS 10+ runtime check** for `CGColorSpaceCopyICCData` (iOS 9 deployment target)

## Test Results

**sRGB:** 3,144 bytes ICC embedded ✅
**Display P3:** 536 bytes ICC embedded ✅
**All tests:** 20/20 passed ✅

Verified with `hexdump` and WebPDemux that ICCP chunk is correctly present.

## Summary by CodeRabbit

* **New Features**
  * WebP image encoding now supports embedding ICC color profiles to ensure accurate color representation during encoding and display.

* **Tests**
  * Added tests verifying ICC profile embedding functionality in WebP-encoded images.
  * Added test coverage for Display P3 color space during WebP encoding.

* **Chores**
  * Updated project configuration files and test asset structure.

### CODE REVIEW

**Comment by dreampiggy** [comment]
LGTM. Will release a version with this PR

---

Released in https://github.com/SDWebImage/SDWebImageWebPCoder/releases/tag/0.15.0

**Comment by lucasfischer** [comment]
Thank you so much for taking a stab at fixing this issue.

The new 0.15.0 release doesn't compile for me with the following errors:
```
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:79:27: error: unknown type name 'SharpYuvTransferFunctionType'
   79 |                           SharpYuvTransferFunctionType transfer_type) {
      |                           ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:91:33: error: unknown type name 'SharpYuvTransferFunctionType'
   91 |                                 SharpYuvTransferFunctionType transfer_type) {
      |                                 ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:108:26: error: unknown type name 'SharpYuvTransferFunctionType'
  108 |                          SharpYuvTransferFunctionType transfer_type) {
      |                          ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:310:29: error: unknown type name 'SharpYuvTransferFunctionType'
  310 |                             SharpYuvTransferFunctionType transfer_type) {
      |                             ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:487:3: error: use of undeclared identifier 'SharpYuvOptions'
  487 |   SharpYuvOptions options;
      |   ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:488:3: error: use of undeclared identifier 'options'
  488 |   options.yuv_matrix = yuv_matrix;
      |   ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:489:3: error: use of undeclared identifier 'options'
  489 |   options.transfer_type = kSharpYuvTransferFunctionSrgb;
      |   ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:489:27: error: use of undeclared identifier 'kSharpYuvTransferFunctionSrgb'
  489 |   options.transfer_type = kSharpYuvTransferFunctionSrgb;
      |                           ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:490:10: error: call to undeclared function 'SharpYuvConvertWithOptions'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  490 |   return SharpYuvConvertWithOptions(
      |          ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:492:72: error: use of undeclared identifier 'options'
  492 |       u_ptr, u_stride, v_ptr, v_stride, yuv_bit_depth, width, height, &options);
      |                                                                        ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:496:33: error: unknown type name 'SharpYuvOptions'
  496 |                                 SharpYuvOptions* options, int version) {
      |                                 ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:506:28: error: use of undeclared identifier 'kSharpYuvTransferFunctionSrgb'
  506 |   options->transfer_type = kSharpYuvTransferFunctionSrgb;
      |                            ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:515:50: error: unknown type name 'SharpYuvOptions'
  515 |                                int height, const SharpYuvOptions* options) {
      |                                                  ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:517:3: error: use of undeclared identifier 'SharpYuvTransferFunctionType'
  517 |   SharpYuvTransferFunctionType transfer_type = options->transfer_type;
      |   ^
/Users/lucas/Library/Developer/Xcode/DerivedData/Project-abkdgniwyfxzcxbgrfotiaonvaki/SourcePackages/checkouts/libwebp-Xcode/libwebp/sharpyuv/sharpyuv.c:572:38: error: use of undeclared identifier 'transfer_type'
  572 |       width, height, &scaled_matrix, transfer_type);
      |                                      ^
15 errors generated.
```

Help would be appreciated.

**Comment by dreampiggy** [comment]
@lucasfischer @KYHyeon 

Maybe you need to upgrade libwebp's min dependency. Means we use API which requires some high version libwebp.

You can use cocoapods or SPM package update to do so. I could not rember which of these API was introduced in libwebp. Maybe @KYHyeon can have a check (so that we can edit the `Package.swift/podspec` to limit a minimum libwebp version to avoid user who still use the old version)

**Comment by dreampiggy** [comment]
Currently you can just use the latest 1.5.0 libwebp, see https://github.com/SDWebImage/libwebp-Xcode/releases

**Comment by dreampiggy** [comment]
Read again about sharpyuv: https://github.com/SDWebImage/libwebp-Xcode?tab=readme-ov-file#about-sharpyuv

Maybe at least v1.3.0

**Comment by KYHyeon** [comment]
It seems that `SharpYuvOptions` and `SharpYuvTransferFunctionType` were introduced in libwebp 1.3.0.

https://chromium.googlesource.com/webm/libwebp/%2B/25d94f473b10882b8bee9288d00539001b692042%5E%21

**Comment by lucasfischer** [comment]
Thank you for the quick help.

My `Package.resolved` says I am using `https://github.com/SDWebImage/libwebp-Xcode.git` `1.5.0`, but I am still getting this error. Locally and in Xcode Cloud. Am I holding this wrong?

**Comment by lucasfischer** [comment]
It didn't work with `libwebp-Xcode` `1.5.0`.

I now added a new entry to my `Package.swift` in which I explicitly pin `libwebp-Xcode` to `1.3.2`, which seems to be the only version that properly works.

```swift
 .package(url: "https://github.com/SDWebImage/libwebp-Xcode.git", exact: "1.3.2"),
```

Previously I didn't have to add the `libwebp-Xcode` package do my dependencies because `SDWebImageWebPCoder` was depending on it with a compatible version.

IMO this should get fixed in this project's `Package.json` file. Should I submit a PR for this?
